[package]
name = "crawler"
version = "0.0.0"
authors = ["Kenneth Powers <ken@kenpowers.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
bytes = "0.5.4"
env_logger = "0.7.1"
flate2 = "1.0.13"
futures = "0.3.3"
lazy_static = "1.4.0"
log = "0.4.8"
metrohash = "1.0.6"
num_cpus = "1.12.0"
regex = "1.3.4"
reqwest = "0.10.1"
serde_json = "1.0.47"
tokio = { version = "0.2", features = ["full"] }
warc_parser = "2.0.0"
