[package]
name = "server"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
engine = { path = "../engine" }
env_logger = "0.7.1"
log = "0.4.8"
prost = "0.6.1"
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "1.8.4", features = ["full"] }
warp = "0.2.1"
sentry = "0.18.0"
